In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


In [2]:
array = np.array([10,20,30])
print(array)

[10 20 30]


In [3]:
array1 = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150])
print(array1.shape)

(15,)


In [4]:
arrayreshape = array1.reshape(3,5)
print(arrayreshape)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]


In [6]:
print("shape: ",arrayreshape.shape)
print("dimension: ",arrayreshape.ndim)
print("data type: ",arrayreshape.dtype.name)
print("size: ", arrayreshape.size)
print("type: ",type(arrayreshape))

shape:  (3, 5)
dimension:  2
data type:  int64
size:  15
type:  <class 'numpy.ndarray'>


In [7]:
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
print(array2.shape)

(3, 4)


In [9]:
zeros= np.zeros((3,4))

In [10]:
zeros[0,0]=5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.empty((4,5))

array([[0. , 0. , 0.3, 1. , 0. ],
       [0. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 0. , 0. ],
       [1. , 0.5, 0. , 0. , 1. ]])

In [13]:
np.arange(10,50,10)

array([10, 20, 30, 40])

In [17]:
x=np.linspace(0,10,40)
print(x)

[ 0.          0.25641026  0.51282051  0.76923077  1.02564103  1.28205128
  1.53846154  1.79487179  2.05128205  2.30769231  2.56410256  2.82051282
  3.07692308  3.33333333  3.58974359  3.84615385  4.1025641   4.35897436
  4.61538462  4.87179487  5.12820513  5.38461538  5.64102564  5.8974359
  6.15384615  6.41025641  6.66666667  6.92307692  7.17948718  7.43589744
  7.69230769  7.94871795  8.20512821  8.46153846  8.71794872  8.97435897
  9.23076923  9.48717949  9.74358974 10.        ]


In [18]:
x = np.array([10,20,30])
y = np.array([40,50,60])

print(x+y)
print(x-y)
print(x**2)

[50 70 90]
[-30 -30 -30]
[100 400 900]


In [20]:
x= np.array([100,200,300,400,500,600,700])

In [21]:
liste = [10,20,30,40]

array = np.array([50,60,70,80])
print(liste)
print(array)

[10, 20, 30, 40]
[50 60 70 80]


In [22]:
array = np.array(liste)
print(array)

[10 20 30 40]


In [23]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [24]:
y=x

z=x

y[0]=5 
print(x,y,z)

[  5 200 300 400 500 600 700] [  5 200 300 400 500 600 700] [  5 200 300 400 500 600 700]


In [25]:
d = a.copy()

In [26]:
a= np.array([1000,2000,3000,4000,5000,6000,7000]) 
print(a)

[1000 2000 3000 4000 5000 6000 7000]


In [27]:
print(a[3])

4000


In [28]:
print(a[2:5])

[3000 4000 5000]


In [29]:
reverse_array = a[::-1] 
print(reverse_array)

[7000 6000 5000 4000 3000 2000 1000]


In [30]:
k = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(k)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
print(k[1,1]) 

print(k[:,1]) 

print(k[1,:]) 

print(k[1,1:4]) 

print(k[-1,:]) 

print(k[:,-1])

7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]


In [32]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
a = array.ravel() 
print(a)

[1 2 3 4 5 6 7 8 9]


In [34]:
array2 = a.reshape(3,3)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
array_transpose = array2.T


print(array_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [36]:
array5 = np.array([[10,20],[30,40],[50,60]])
print(array5)

[[10 20]
 [30 40]
 [50 60]]


In [37]:
array5.resize((2,3)) 
print(array5)

[[10 20 30]
 [40 50 60]]
